parameters:
  highcharts.twig_extension.class: HighchartsBundle\Twig\HighchartsExtension

services:
  ob_highcharts.twig.highcharts_extension:
    class: "%highcharts.twig_extension.class%"
    tags:
        - { name: twig.extension }
