name: Markdown Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint
        uses: DavidAnson/markdownlint-cli2-action@v14
        with:
          globs: '*.md'
